default:
  image: node:lts
stages:
  - build
  - test
cache:
  paths:
    - node_modules/
build-server:
  stage: build
  script:
    - cd server
    - npm ci -s
    - npm run build
server-unit-test:
  stage: test
  script:
    - cd server
    - npm ci -s
    - npm run test:cov
server-e2e-test:
  stage: test
  script:
    - cd server
    - npm ci -s
    - npm run test:e2e