version: '3.8'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args: 
      - REACT_APP_SERVER_URL=http://localhost:3000
    ports:
      - 80:80
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - "MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017"
  database:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}"
